### ISSUE TITLE
need function to delete appointment from db by email+start+end

### ISSUE THREAD

**Issue by skaliak** [skaliak/dt520#23]
When a cancellation email comes in, we need to find the appointment in the db and delete it.  We won't know what the row id is, so we can't use the existing delete function.

A new db function is needed that executes sql that deletes a row that matches the parsed appointment.  `email + start + end` is enough to uniquely identify the appointment.

**Comment by LChristakis** [comment]
function should be able to find row based on `email + start` since two appointments cannot share a start time
