### ISSUE TITLE
need uid lookup for the appointment cancellation icalendar email

### ISSUE THREAD

**Issue by skaliak** [skaliak/dt520#26]
on #24 it just occurred to me that the whole point of the uid being stored in the db is so that it can be used if a cancellation message needs to be sent. 

If a plaintext cancellation comes in, then the appointment row needs to be looked up in the db by email + start + end.  This way the icalendar string will have the uid on it.

Btw, the name of the module is uuid, and so is the name of the db column, but everywhere else (variable names, dict key, etc) it's uid.  Sorry about that :grimacing:

**Comment by LChristakis** [comment]
@skaliak so for this issue we should need a new regex in procmail and a new query in db_connector, correct?

**Comment by skaliak** [comment]
@LChristakis There's already a regex in email_parser that determines whether an email is a confirmation or a cancellation.  We just need a new query in db_connector.

**Comment by LChristakis** [comment]
Sorry this took so long. Added a function and corresponding query to `db_connector.py` that deletes appointments matching `email` and `start`. Can someone test to check my work?

**Comment by skaliak** [comment]
ok... I already implemented the delete function a while ago:
https://github.com/skaliak/dt520/pull/31

What we still need is a *lookup* function that finds a db record by start and email.

**Comment by LChristakis** [comment]
Sorry for the mix-up, I think I'm having trouble understanding what module will be calling this function. Should the lookup be performed by the procmail filter or the icalendar generator?

**Comment by skaliak** [comment]
Either could work, but I think it would make the most sense to have the icalendar generator call this function, which would happen if it is generating a cancellation.  That way there doesn't need to be an extra parameter (for uuid) passed to the icalendar generator function by the procmail filter.

**Comment by LChristakis** [comment]
Ok, let's try this again; just pushed a new commit to the `Peter_procmail_filter` branch. The new function is `get_matching_uid` and it's in `db_connector.py`. (Let me know if you think it should be named `get_matching_uuid` instead.) Also, I decided to put the function call in `sas_procmail_filter.py`. My reasons:
*procmail filter already had db_connector configured and a db Client created
*in its current form, `generate_icalendar_email` expects the `data` dict it is passed by `sas_procmail_filter` to provide a uuid.
*if procmail action is 'confirm', the `data` dict will include a uuid. I felt that this should be mirrored for 'cancellation'.

Let me know what you think; it's not a difficult change. And let me know if you have any problems with the code.

**Comment by skaliak** [comment]
Ahh ok, that makes perfect sense.  Thanks!

**Comment by skaliak** [comment]
This can be closed, right?

**Comment by LChristakis** [comment]
Yup!
