### ISSUE TITLE
Error in curses cli when appointment is outside of normal workday time range

### ISSUE THREAD

**Issue by skaliak** [skaliak/dt520#29]
See this comment for details:
https://github.com/skaliak/dt520/pull/28#issuecomment-75783468

**Comment by LChristakis** [comment]
This bug is fixed, but I found unexpected behavior; on my computer each day column only has space for about 5 hours (40 lines/4 lines per half-hour appointment) This means any appointments after around 3pm fail to show up.

**Comment by LChristakis** [comment]
Issue resolved; appointments starting above the screen (vpos 0) or extending below the day column (vpos + height < day_h) are no longer drawn.
