### ISSUE TITLE
Implement iCalender generator

### ISSUE THREAD

**Issue by skaliak** [skaliak/dt520#6]

**Comment by skaliak** [comment]
@LChristakis @mhvoodoo could one of you please make an attempt at this?  It's really just a lot of string formatting... but it could get complicated.  This is one of our milestones for this week.  If you want to do it, just assign yourself to the issue.

**Comment by mhvoodoo** [comment]
Hey guys sorry for being mia, I will looked into some of the functions but haven't given it a genuine shot yet. I'll try to get something in today after work and definitely before the end of the week!

**Comment by skaliak** [comment]
Thanks for working on this, Man.
