### ISSUE TITLE
Implement Curses CLI

### ISSUE THREAD

**Issue by skaliak** [skaliak/dt520#7]

**Comment by skaliak** [comment]
@LChristakis @mhvoodoo please check out the branch called Peter_curses.  Run the file called c_view.py.  It still needs comments for functions, but hopefully it should be possible to figure out how it works based on the names of the functions and variables.

This is currently using the module data_faker as a substitute for the db_connector module.  data_faker has the same function names as db_connector, but it just generates appointments on the fly instead of querying the database.

**Comment by LChristakis** [comment]
@skaliak @mhvoodoo Peter, this looks fantastic. I'm getting errors when I attempt to delete an appointment:

File "c_view.py", line 18, in __init__
self.ui_loop()
File "c_view.py", line 91, in ui_loop
self.model.delete_selected_apt()
File "c_model.py", line 52, in delete_selected_apt
id = apt_to_delete['id']
KeyError: 'id'

But I'm going to take a look and try to fix it myself. I'm also planning on going through the code and adding comments as best I can; I'll let you know if I have trouble understanding what's going on. On the whole though the CLI functions really well!

**Comment by skaliak** [comment]
@LChristakis probably the fake data generator isn't including an 'id' key.  Delete isn't going to do anything with the fake data, anyway.  Might be a good idea to rebase this branch so the db_connector functions are accessible.

**Comment by LChristakis** [comment]
I'm rebasing the branch and integrating with db_connector, but I noticed that c_model.py has the following function call:

self.db.query_appointments_by_week(self.week)

I don't think db_connector has this functionality... how do you think I should address this? I wasn't sure if I should make a new branch of db_connector and add it there, or just put it in c_model.py. I'm leaning towards putting it in db_connector, but I'd like to see what you think.

**Comment by LChristakis** [comment]
@skaliak Peter is this branch supposed to be closed? Sorry I've been AWOL, assignment 4 for CS419 was giving me a lot of trouble. Should be much freer this week.

**Comment by skaliak** [comment]
@LChristakis  I closed it, because it's definitely true that the curses CLI has been implemented.  Whatever bugs it still has should have separate issues opened for them.  We should probably merge all the outstanding pull requests before moving on to bugfixes, so things don't get too fragmented.

**Comment by LChristakis** [comment]
Agreed. Tried to debug this a little today, but ran into problems because changes in Peter_query_by_week need to be integrated. I'd like to test Peter_query_by_week, merge with Master and then rebase Peter_curses from master but unfortunately Peter_query_by_week does not include workweek.py, so I'm not sure how to go about testing.

**Comment by skaliak** [comment]
How about this:
1. checkout Peter_curses and make a copy of workweek.py
2. checkout Peter_query_by_week, copy workweek.py to the folder, but don't `git add` it
3. write the test, using the local copy of workweek.py

The test could work like this:
1. create a workweek instance and set it to some week in the future by calling next_week() a few times.
2. get a date in that week and create an appointment on that day
3. call query_by_week() and pass the workweek object
4. check that the appointment created in step 2 was created
